### PR TITLE
Create Test-ADCredential.ps1

### PR DESCRIPTION
**Pull request by AnthonyKersten**

### CODE REVIEW

**Comment by lazywinadmin** [comment]
Thanks @AnthonyKersten !
Would you mind renaming the folder to something like: `AD-TOOL-Test-ADCredential` ?

**Review by lazywinadmin — CHANGES_REQUESTED** [review]
Thanks @AnthonyKersten !
Would you mind renaming the folder to something like: `AD-TOOL-Test-ADCredential` ?

**Comment by AnthonyKersten** [comment]
I've renamed the folder

**Review by lazywinadmin — APPROVED** [review]

**Comment by lazywinadmin** [comment]
Thanks @AnthonyKersten ! :+1:

**Pull request merged**
